#!/bin/bash
# Copyright (c) 2015 Online Labs Cloud Team <cloud-team@labs.online.net>
# Released under the MIT license.

for device in /dev/nbd[^0]*
do
    nbd-client -c $device && nbd-client -d $device
done
