#!/bin/bash

get_metadata() {
    /usr/local/bin/oc-metadata --cached
}

get_value() {
    get_metadata | grep "^$1=" | cut -d= -f2 | sed "s/^['\"]//;s/['\"]$//"
}

sync_connect_extra_volumes() {
    nbd_id=0
    for volume in $(get_value VOLUMES)
    do
	# ignore root nbd device, it is handled differently.
	test $nbd_id -eq 0 && continue

	export_uri=$(get_value "VOLUMES_${nbd_id}_EXPORT_URI")
	nbd_host=$(echo $export_uri | sed 's|nbd://\(.*\):.*|\1|')
	nbd_port=$(echo $export_uri | sed 's|nbd://.*:\(.*\)|\1|')

	device=$("/dev/nbd${nbd_id}")
	until nbd-client -c $device
	do
	    nbd-client -b 4096 -p $nbd_host $nbd_port
	    sleep 5
	done
	nbd_id=$((nbd_id + 1))
    done
}

sync_connect_extra_volumes
